class ValidatorFittingError(Exception):
    """Raised in Validators if there is a problem with the fitting process."""

    pass
